name: contextual_message
version: 1.0.4
description: Provides a data type useful for contextual logging
documentation: https://github.com/Workiva/contextual_message
homepage: https://github.com/Workiva/contextual_message

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  dart_dev: '>=3.9.0 <5.0.0'
  dart_dev_workiva:
    hosted:
      name: dart_dev_workiva
      url: https://pub.workiva.org
    version: ^2.0.1
  dart_style: '>=1.3.14 <3.0.0'
  dependency_validator: '>=2.0.3 <4.0.0'
  test: ^1.16.5
  workiva_analysis_options: ^1.3.0

dependency_overrides:
  dart_dev_workiva:
    git:
      url: ssh://git@github.com/Workiva/dart_dev_workiva.git
      ref: FEDX-41
