name: contextual_message
version: 1.0.12
description: Provides a data type useful for contextual logging
documentation: https://github.com/Workiva/contextual_message
homepage: https://github.com/Workiva/contextual_message

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  build_runner: ^2.0.0
  build_test: ^2.0.0
  dart_dev: ^4.0.0
  dart_style: ^2.0.0
  dependency_validator: ^3.0.0
  test: ^1.16.5
  workiva_analysis_options: ^1.3.0
