name: contextual_message
version: 1.0.2
description: Provides a data type useful for contextual logging
documentation: https://github.com/Workiva/contextual_message
homepage: https://github.com/Workiva/contextual_message

environment:
  sdk: '>=2.11.0 <3.0.0'

dev_dependencies:
  dart_dev: '>=3.9.0 <5.0.0'
  dart_dev_workiva:
    hosted:
      name: dart_dev_workiva
      url: https://pub.workiva.org
    version: ^2.0.1
  dart_style: ^1.3.14
  dependency_validator: ^2.0.3
  test: ^1.16.5
  workiva_analysis_options: ^1.3.0
