name: CI

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

permissions:
  contents: read
  id-token: write

jobs:
  package:
    runs-on: [self-hosted, small]
    steps:
      - uses: actions/checkout@v3
      - uses: Workiva/gha-dart/create-pub-package@v0.3.25

  checks:
    uses: Workiva/gha-dart/.github/workflows/checks.yaml@v0.3.25

  unit-tests:
    uses: Workiva/gha-dart/.github/workflows/test-unit.yaml@v0.3.25

  semver-audit:
    uses: Workiva/gha-dart/.github/workflows/semver-audit-dart.yaml@v0.3.25